version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/usr/src/api/dist
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      REDIS_URL: 'redis://redis:6379'
    command: nodemon dist/index.js
